### ISSUE TITLE
Activity change

### ISSUE THREAD

**Issue by sohayb** [danielemaddaluno/Android-Update-Checker#5]
Hello,
When the user changes the activity so the activity is destroyed or something, the app would crash and the cause is calling show_dialog_you_are_not_updated() on an activity that is already closed. Can you please add the support to show a notification with update and cancel actions rather than a dialog?
Thanks

**Comment by syrakozz** [comment]
+1

**Comment by danielemaddaluno** [comment]
If I correctly understand, that is due to the asynchronicity of the call to the dialog (it could be called in a later moment, too late for the activity which is already dead in your example)
Yes, I can add support to notification, sure. But do you think that could exist some trick to bypass this problem with the dialogs? Maybe a control on the activity variable?
Let me know.

**Comment by sohayb** [comment]
The better approach is to show an actionable notification. But regarding the dialog, if you want to show a dialog not related to the passed activity, you take the passed activity application context (when passed) and hold a reference to it, and when you finish checking, you show an activity (with a dialog theme) using an intent started with the previously held application context.

**Comment by drbest3n** [comment]
Thanks
